# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8927c13c66560af711553e24367bc519bab1aca51f707301a5b6b81c44edddd3b85d1a56ac87153870831b374b4e56eba17d82ef259ed9a26edf89760e7ae5e0

test:
  secret_key_base: 8bc3e0639d153b197b3ccbed38ec9429aecbff4d1d142d130d7596135c816ee72a1d3a4160ffe2fee2523e66065b65d49efd6c667c8eb859c030b86d0459ad6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
